app/routes.php
<?php

Route::get('news/How-APIs-Accelerate-Business', function() { return Redirect::to('/news/how-apis-accelerate-business', 301); });
Route::get('news/The-Tablet-Experience-Survey-Says-More-Desktop-Less-Smartphone', function() { return Redirect::to('/news/the-tablet-experience-survey-says-more-desktop-less-smartphone', 301); });
Route::get('posts/Tablet-Owners-Content-and-Experience-Preferences-When-Browsing-the-Web', function() { return Redirect::to('/news/tablet-owners-content-and-experience-preferences-when-browsing-the-web', 301); });
Route::get('news/Avenue-32-Brings-Element-Of-Discovery-Back-To-Online-Shopping', function() { return Redirect::to('/news/avenue-32-brings-element-of-discovery-back-to-online-shopping', 301); });
Route::get('news/Retailers-experiencing-bad-side-effects-from-tablets%20', function() { return Redirect::to('/news/retailers-experiencing-bad-side-effects-from-tablets', 301); });
Route::get('news/Brands-Slow-to-Create%20Tablet-Specific-Experiences', function() { return Redirect::to('/news/brands-slow-to-create-tablet-specific-experiences', 301); });
Route::get('news/Avenue-32-sees-mobile-orders-increase-400-pc-after-multichannel-facelift', function() { return Redirect::to('/news/avenue-32-sees-mobile-orders-increase-400-pc-after-multichannel-facelift', 301); });
Route::get('news/10-interesting-digital-marketing-stats-we-ve-seen-this-week', function() { return Redirect::to('/news/10-interesting-digital-marketing-stats-we-have-seen-this-week', 301); });
Route::get('news/Medifast-Enhances-Business-Model-With-Mobile-Weight-Loss-Tools', function() { return Redirect::to('/news/medifast-enhances-business-model-with-mobile-weight-loss-tools', 301); });
Route::get('news/Tablet-Owners-Content-and-Experience-Preferences-When-Browsing-the-Web', function() { return Redirect::to('/news/tablet-owners-content-and-experience-preferences-when-browsing-the-web', 301); });
Route::get('news/chain-store-agenbsp-mobile-shopping-skyrockets-thanksgiving-and-black-friday-1', function() { return Redirect::to('/news/mobile-shopping-skyrockets-thanksgiving-and-black-friday', 301); });
Route::get('news/new-media-knowledge-new-report-reveals-top-tips-for-making-the-most-of-mobile-in-store-1', function() { return Redirect::to('/news/new-report-reveals-top-tips-for-making-the-most-of-mobile-in-store', 301); });
Route::get('news/journaldunetcom-marks-and-spencer-va-deacuteployer-agrave-linternational-son-savoir-faire-multicanal-1', function() { return Redirect::to('/news/marks-and-spencer-va-deployer-a-l-international-son-savoir-faire-multicanal', 301); });
Route::get('news/marketwired-usablenet-holiday-shopping-index-shows-highest-spike-in-mobile-activity-on-cyber-monday-1', function() { return Redirect::to('/news/usablenet-holiday-shopping-index-shows-highest-spike-in-mobile-activity-on-cyber-Monday', 301); });
Route::get('archive', function() { return Redirect::to('/news', 301); });
Route::get('news/marketwired-usablenet-named-in-independent-mobile-commerce-solution-provider-report-1', function() { return Redirect::to('/news/usablenet-named-in-independent-mobile-commerce-solution-provider-report', 301); });
Route::get('news/Is-Tablet-Specific-Better-than-Responsive', function() { return Redirect::to('/news/is-tablet-specific-better-than-responsive', 301); });
Route::get('news/Avenue-32-provides-mobile-design-showcase', function() { return Redirect::to('/news/avenue-32-provides-mobile-design-showcase', 301); });
Route::get('news?page=4', function() { return Redirect::to('/news/page4', 301); });
Route::get('news/new-media-knowledge-cyber-monday-mega-monday-mobile-monday-more-like-1', function() { return Redirect::to('/news/cyber-monday-mega-monday-mobile-monday-more-like', 301); });
Route::get('news/eseller-five-ways-to-close-the-multichannel-loop-1', function() { return Redirect::to('/news/five-ways-to-close-the-multichannel-loop', 301); });
Route::get('news/mediapost-holiday-wrap-mobile-jumps-in-visits-order-size-and-sales-1', function() { return Redirect::to('/news/holiday-wrap-mobile-jumps-in-visits-order-size-and-sales', 301); });
Route::get('news/Usablenet-Experience-important-for-tablet-shoppers', function() { return Redirect::to('/news/usablenet-experience-important-for-tablet-shoppers', 301); });

Route::filter('permissions', 'PermissionsFilter');

Route::group(array('before' => 'permissions'), function()
{
	Route::resource('menus', 'MenuController');
	Route::resource('pages', 'PageController');
	Route::get("/pages/{id}/page-manager", [
		"as"   => "page-manager",
		"uses" => "PageController@pageManager"
	]);
	Route::put("/pages/{id}/update-page", [
		"as"   => "update-page",
		"uses" => "PageController@updatePage"
	]);
	Route::post("/pages/store-page", [
		"as"   => "store-page",
		"uses" => "PageController@storePage"
	]);
	Route::get("get-page-list", [
		"as"   => "page-list",
		"uses" => "PageController@getPageList"
	]);
	Route::get("scan-template/{template_id}", [
		"as"   => "scan-template",
		"uses" => "PageController@scanTemplate"
	]);
	Route::post("/ckeditor/file-upload", [
		"as"   => "file-upload",
		"uses" => "PageController@fileUpload"
	]);

	Route::get("/menu-items/create/{menu_id}", [
		"as"   => "create-menu-item",
		"uses" => "MenuItemController@create"
	]);
	Route::post("/menu-items/store-break/{menu_id}", [
		"as"   => "menu-item-store-break",
		"uses" => "MenuItemController@storeBreak"
	]);
	Route::resource('menu-items', 'MenuItemController');

//	Route::get("slug-them-all", [
//		"as"   => "slug-them-all",
//		"uses" => "PostController@slugThemAll"
//	]);

	Route::resource('products', 'ProductController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('case-studies', 'CaseStudyController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('careers', 'CareerController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('clients', 'ClientController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('news', 'PostController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('cetegories', 'CategoryController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('authors', 'AuthorController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('locations', 'LocationController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('partners', 'PartnerController', array('only' => array('update', 'store', 'destroy')));
	Route::resource('leaders', 'LeaderController', array('only' => array('update', 'store', 'destroy')));
});

Route::resource('products', 'ProductController', array('only' => array('show'), 'names' => array('show' => 'products.{slug}')));
Route::resource('news', 'PostController', array('only' => array('show')));
Route::resource('clients', 'ClientController', array('only' => array('show'), 'names' => array('show' => 'clients.{slug}')));
Route::resource('partnerships', 'PartnerController', array('only' => array('show'), 'names' => array('show' => 'partnerships.{slug}')));

Route::get("blog", [
    "as"   => "blog",
    "uses" => "PostController@blog"
]);

Route::get("blog/{slug}", [
    "as"   => "blog-article",
    "uses" => "PostController@showBlog"
]);

Route::get('/capabilities', [
	"as"   => "services-page",
	"uses" => "ServicesController@show"
]);

Route::get("search-blog/{q?}/{category?}/{tag?}", [
    "as"   => "search",
    "uses" => "PostController@search",
	function($q = null) {
		return $_GET['q'];
	},
    function($category = null) {
        return $category;
    },
    function ($tag = null) {
        return $tag;
    }
]);

Route::get("news", [
	"as"   => "insights",
	"uses" => "PostController@index"
]);

Route::get("/archive/{year}", [
	"as"   => "news-archive",
	"uses" => "PostController@archive"
]);

Route::get("/archive", function() {
	return Redirect::action('PostController@index');
});

Route::any("model-values", function(){
	$careers = array(
			'Career' => array(
					'careers' => 'all'
				)
		);

	$casestudies = array(
			'CaseStudy' => array(
					'caseStudies' => 'all'
				)
		);

	$posts = array(
			'Post' => array(
					'posts' => 'all'
				)
		);

	return $posts;

});

Route::any('webhooks/zencoder/{table}/{field}/{id}', [
	"as"   => "zencoder_webhook",
	function($table, $field, $id){
		Event::fire('webhook.zencoder', array($table, $field, $id));
	}
]);

Route::get("/sitemap.xml", [
	"as"   => "sitemap",
	"uses" => "PageController@sitemap"
]);

Route::get("/rss/{version}", [
	"as"   => "rss",
	"uses" => "PostController@rss"
]);
Route::get("/blogrss/{version}", [
    "as"   => "blogRSS",
    "uses" => "PostController@blogRSS"
]);
Route::get("/kcrss/{version}", [
    "as"   => "kcRSS",
    "uses" => "PostController@kcRSS"
]);

Route::get('404', array('uses' => 'RouteErrorController@fourZeroFour'));

Route::get("/login", [
	"as"   => "login",
	"uses" => "UserController@login"
]);

Route::get("/logout", [
	"as"   => "logout",
	"uses" => "UserController@logout"
]);

Route::post("/attempt-login", [
	"as"   => "loginAction",
	"uses" => "UserController@loginAction"
]);

Route::post('send-email', [
		'as' => 'send-email',
		'uses' => 'ContactController@email'
	]);

Route::get('/', [
	"as"   => "tms-page",
	"uses" => "PageController@show"
]);

Route::get('{slug}', [
	"as"   => "tms-page",
	"uses" => "PageController@show"
])->where('slug', '[A-Za-z0-9%\-\/]+');



function array_merge_assoc($arr1, $arr2){

	$final_arr = $arr1 + $arr2;

	foreach ($arr1 as $key => $val)
	{
		foreach($arr2 as $key2 => $val2)
		{
			if ($key2 == $key)
			{
				$final_arr[$key] = $final_arr[$key] + $arr2[$key];
			}
		}
	}

	return $final_arr;
}

app/models/Post.php
<?php

use Tms\ThingmsModel;

class Post extends ThingmsModel {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'posts';

	/**
	 * Fields that are guarded against mass assignment
	 * @var array
	 */
	protected $guarded = array('id', 'created_at', 'updated_at');

	/**
	 * Validation rules when creating a new car
	 * @var array
	 */
	public $storeRules = array(
		'slug'  => 'required|unique:tms_pages,slug',
	);

	/**
	 * Validation rules when updating a car
	 * @var array
	 */
	public $updateRules = array(
	);

	/**
	 * Validation rules when updating a car
	 * @var array
	 */
	public $updateFieldsRules = array(
	);

	/**
	 * Validation messages to display on error
	 * @var array
	 */
	public $messages = array(
		'slug' => 'Your page must have a unique slug and cannot be empty.',
	);

    public static function boot()
    {
        parent::boot();

        Post::saving(function($post)
        {
            if (isset($post->tags)) {

                $tagIds = array();
                $tags = explode(',', $post->tags);
                $post->updated_at = date('Y-m-d H:i:s');

                foreach($tags as $t) {
                    if (trim($t) !== '') {
                        $tag = Tag::firstOrNew(array('name' => trim($t)));
                        $tag->save();
                        $tagIds[] = $tag->id;
                    }
                }

                Config::set('post.tagids', $tagIds);
                unset($post->tags);
            }
        });

        Post::saved(function($post)
        {
            $tagIds = Config::get('post.tagids');

            if($tagIds) {
                $post->tags()->sync($tagIds);
            }
        });
    }

	public function category(){
		return $this->belongsTo('Category');
	}

	public function author(){
		return $this->belongsTo('Author');
	}

    public function tags(){
        return $this->belongsToMany('Tag');
    }

	public function getMainImageAttribute($value)
	{
		return $this->getImageAttr($value);
	}

	public function getImageThumbAttribute($value)
	{
		return $this->getImageAttr($value);
	}

}

app/views/usablenet/about-us.blade.php
@extends('layouts.master')

@section('topform')
	<div class="topform">
		<div class="container">&nbsp;</div>
	</div>
@stop

@section('main')
	<section class="section full-width page-title-slice" tabindex="0" style="background-color:{{$page->title_background_color}};background-image:url({{ URL::asset($page->title_background->src) }});color:{{ $page->title_text_color }}">
		<div class="container">
			<div class="row-fluid">
				<div class="span6">
					<h1 class="sub-title tms-editor light-gray mbz tms-inline" {{ $page->editor('title_subtitle', 'inline') }}>{{ $page->title_subtitle }}</h1>
					<h2 class="title tms-editor tms-inline" {{ $page->editor('title_title', 'inline') }}>{{ $page->title_title }}</h2>
				</div>
			</div>
			<?php if(TmsAuth::isInGroup('Administration')) { ?>
			<button class="tms-editor tms-btn" {{ $page->editor('title_background', '.page-title-slice', null, array('updateAttribute' => 'style[background-image]', 'type'=>'image')) }}>Edit Section Background</button>
			<button class="tms-editor tms-btn" {{ $page->editor('title_text_color', '.page-title-slice', null, array('updateAttribute' => 'style[color]', 'type'=>'color')) }}>Edit Text Color</button>
			<button class="tms-editor tms-btn" {{ $page->editor('title_background_color', '.page-title-slice', null, array('updateAttribute' => 'style[background-color]', 'type'=>'color')) }}>Edit Background Color</button>
			<?php } ?>
		</div>
	</section>

	<section class="section full-width" tabindex="0">
		<div class="container">
			<div class="row-fluid">
				<div class="span7">
					@if($page->two_column_subtitle !== '' || TmsAuth::isInGroup('Administration'))
					<h3 class="title tms-editor tms-inline" {{ $page->editor('two_column_subtitle', 'inline') }}>{{ $page->two_column_subtitle }}</h3>
					@endif
					@if($page->two_column_title !== '' || TmsAuth::isInGroup('Administration'))
					<h3 class="fs24 lh15 tms-editor tms-inline" {{ $page->editor('two_column_title', 'inline') }}>{{ $page->two_column_title }}</h3>
					@endif
				</div>
			</div>
			<div class="row-fluid mt h40">
				<div class="span6">
					<div class="tms-editor tms-inline" {{ $page->editor('two_column_column_1_title', 'inline') }}><strong>{{ $page->two_column_column_1_title }}</strong></div>
				</div>
				<div class="span6">
					<div class="tms-editor tms-inline" {{ $page->editor('two_column_column_2_title', 'inline') }}><strong>{{ $page->two_column_column_2_title }}</strong></div>
				</div>
			</div>
			<div class="row-fluid mt">
				<div class="span6">
					<div class="tms-editor tms-inline" {{ $page->editor('two_column_column_1_description', 'inline') }}>{{ $page->two_column_column_1_description }}</div>
				</div>
				<div class="span6">
					<div class="tms-editor tms-inline" {{ $page->editor('two_column_column_2_description', 'inline') }}>{{ $page->two_column_column_2_description }}</div>
				</div>
			</div>
		</div>
	</section>

	<section tabindex="0" class="section full-width page-three_column-slice"  style="background-color:{{$page->three_column_background_color}};color:{{ $page->three_column_text_color }}">
		<div class="container color white mb">
			<div class="row-fluid mt h40">
				<div class="span12">
					<h3 class="tms-editor title tms-inline" {{ $page->editor('three_column_title', 'inline') }}>{{ $page->three_column_title }}</h3>
				</div>
			</div>
			<div class="row-fluid mt h10">
				<div class="span4">
					<div class="tms-editor tms-inline" {{ $page->editor('three_column_column_1_description', 'inline') }}>{{ $page->three_column_column_1_description }}
					</div>
				</div>
				<div class="span4">
					<div class="tms-editor tms-inline" {{ $page->editor('three_column_column_2_description', 'inline') }}>{{ $page->three_column_column_2_description }}
					</div>
				</div>
				<div class="span4">
					<div class="tms-editor tms-inline" {{ $page->editor('three_column_column_3_description', 'inline') }}>{{ $page->three_column_column_3_description }}
					</div>
				</div>
			</div>
			<?php if(TmsAuth::isInGroup('Administration')) { ?>
			<button class="tms-editor tms-btn" {{ $page->editor('three_column_background', '.page-three_column-slice', null, array('updateAttribute' => 'style[background-image]', 'type'=>'image')) }}>Edit Section Background</button>
			<button class="tms-editor tms-btn" {{ $page->editor('three_column_text_color', '.page-three_column-slice', null, array('updateAttribute' => 'style[color]', 'type'=>'color')) }}>Edit Text Color</button>
			<button class="tms-editor tms-btn" {{ $page->editor('three_column_background_color', '.page-three_column-slice', null, array('updateAttribute' => 'style[background-color]', 'type'=>'color')) }}>Edit Background Color</button>
			<?php } ?>
		</div>


	</section>

@stop

@section('modals')
	<div id="modal-video" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="Video Modal" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
		<div class="modal-body">
			<video id="video-player" autoplay="true" controls="true" preload="none" width="100%">
				<p>Your user agent does not support the HTML5 Video element.</p>
			</video>
		</div>
	</div>
@stop

app/views/usablenet/case-studies.blade.php
<section class="section full-width padding bottom">
	<div class="container" style="
    border-top: 1px solid #e5e5e5;
">
		<div class="row-fluid">
			<div class="span12 left-col">
				<h3 class="title mbz" style="
    margin-bottom: 30px;
    margin-top: 40px;
">Case Studies</h3>
 
				<div class="row-fluid">
					<div class="span4">
						<a href="/clients/fedex">
						<img class="responsive" alt="fedex logo" src="{{ URL::to('images/casestudy-image-1.png')}}">
						</a>
					</div>
					<div class="span4">
						<a href="/clients/fedex">
						<img class="responsive" alt="Hyatt logo" src="{{ URL::to('images/casestudy-image-2.png')}}">
						</a>
					</div>
					<div class="span4"><a href="/clients/fedex">
						<img class="responsive" alt="Dell logo" src="{{ URL::to('images/casestudy-image-3.png')}}">
						</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>

app/views/usablenet/contact-form-case-studies.blade.php
<section class="section full-width padding bottom contact-us">
	<div class="container">
		<div class="row-fluid">
			<div class="span6 left-col">
				<h3 class="title mbz">Select Case Studies</h3>

				<div class="row-fluid">
					<div class="span12">
						<ul class="small-case-study-grid">
							@for ($i=0; $i < 4; $i++)

							<li class="span6 mlz span-tab-12 span-dt-6">
								<div>
									<a href="{{ URL::action('ClientController@show', $caseStudies[$i]->slug) }}"><img src="{{ URL::asset($caseStudies[$i]->small_logo->src) }}" width="124" height="88" alt="{{$caseStudies[$i]->small_logo->alt}}" class="title"></a>
								</div>
							</li>

							@endfor
						</ul>
					</div>
				</div>
			</div>

			<div class="span6 right-col">
				<div class="inline-anchor"><div id="footer-contact"></div></div>


				@if(Session::has('message-success-footer-contact'))
					<h3 class="title mbz" id="contact">Thank You. We will contact you shortly.</h3>
				@else
					<h3 class="title mbz" id="contact">Contact Us</h3>
				@endif

				@if(Session::has('message-fail-footer-contact'))
					<h4 class="text-error title mbz">{{ Session::get('message-fail-footer-contact') }}</h4>
				@endif

				<div class="mt h20">
					{{ Form::open(array('action' => 'ContactController@email')) }}
						{{Form::hidden('program_name', 'Website Contact Us')}}
						{{Form::hidden('from', 'footer-contact')}}
						<div class="clear h1">&nbsp;</div>

						<div class="row-fluid">
							<div class="span12">
								{{ Form::text('FirstName', null, array('class' => 'input-block-level', 'placeholder' => 'First Name')) }}
								{{ $errors->first('FirstName'); }}
							</div>
						</div>

						<div class="row-fluid mt h20">
							<div class="span12">
								{{ Form::text('LastName', null, array('class' => 'input-block-level', 'placeholder' => 'Last Name')) }}
								{{ $errors->first('LastName'); }}
							</div>
						</div>

						<div class="row-fluid mt h20">
							<div class="span12">
								{{ Form::text('Email', null, array('class' => 'input-block-level', 'placeholder' => 'Email Address')) }}
								{{ $errors->first('Email'); }}
							</div>
						</div>

						<div class="row-fluid mt h20">
							<div class="span12">
								{{ Form::text('Company', null, array('class' => 'input-block-level', 'placeholder' => 'Organization\'s Name')) }}
								{{ $errors->first('Company'); }}
							</div>
						</div>

						<div class="row-fluid mt h20">
							<div class="span12">
								{{ Form::textarea('ContactUs_Message__c', null, array('class' => 'input-block-level', 'placeholder' => 'Message', 'rows' => '2')) }}
							</div>
						</div>

						<div class="row-fluid">
							<div class="span4 fr">
								<button type="submit" class="ptl pbl btn btn-success btn-flat btn-block mt h20">Send</button>
							</div>
						</div>
					{{ Form::close() }}
				</div>
			</div>

		</div>
	</div>
</section>

app/views/usablenet/contact-form-modal.blade.php
<section class="full-width bottom contact-us">
		<div class="form-body">
			<h3 class="title mbz" id="contact">Contact Us</h3>
			<div id="modal-form-contactus" class="form-wrap">
				
			</div>
		</div>
</section>
<a href="#" class="modal-close-btn" data-modal-close>&times;</a>

app/views/usablenet/post.blade.php
@extends('layouts.master')

@section('topform')
	<div class="topform">
		<div class="container">&nbsp;</div>
	</div>
@stop

@section('main')

	<section class="section full-width breadcrumbs">
		<div class="container">
			<div class="row-fluid">
				<div class="span2 section-name">
					<p>News &amp; Events</p>
				</div>
				<div class="span10 crumbs mz">
					<ul class="mz">
						{{ Usablenet::buildcrumbs(URL::current()) }}
					</ul>
				</div>
			</div>
		</div>
	</section>
	<section id="usablenet-blog-post" class="section full-width post">
		<div class="container">
			<div class="row-fluid">
				<?php if ( ! is_null($post) && ! empty($post) ) : ?>
					<div class="span2 text-right post-date">
						<p><strong>{{ date('M j', strtotime($post->posted_on)) }}</strong><br />
						{{ date('Y', strtotime($post->posted_on)) }}
					</div>
					<div class="span7 span-dt-10 span-tab-10 mb">
						<div class="title mtz mb h40 post-title">
							<?php

												$title = preg_match_all("/<p>(.*)<\/p>/",$post->title,$matches);

											if (isset($matches[1]) && isset($matches[1][0]))
											echo '<h2>'.strip_tags($matches[1][0]) . '</h2>';

											if (isset($matches[1]) && isset($matches[1][1]))
											echo '<h1>'.  strip_tags($matches[1][1]) . '</h1>';
											?>
						</div>

						@if($post->main_image->src !== '' && $post->main_image->src !== null)
						<img src="{{ URL::asset($post->main_image->src) }}" alt="{{ $post->main_image->alt }}" class="responsive">
						@endif

						<div class="mt h20"><!-- WYSIWYG -->
							{{ $post->article }}
						</div>
					</div>
				<?php else : ?>
					<div class="span2 text-right">
						There is no news article with this title
					</div>
				<?php endif; ?>
				<div class="span3 span-dt-12 span-tab-12 text-center">

					<?php if(TmsAuth::isInGroup('Administration')) { ?>
						<div class="container">
							<span class="tms-editor" {{ $post->editor('title', 'null', 'edit_post', array('type'=>'wysiwyg'))}}></span>
							<span class="tms-editor" {{ $post->editor('slug', 'null', 'edit_post')}}></span>
							<span class="tms-editor" {{ $post->editor('category_id', 'null', 'edit_post', array('type'=>'select', 'options'=>$categoryList)) }}></span>
							<span class="tms-editor" {{ $post->editor('author_id', 'null', 'edit_post', array('type'=>'select', 'options'=>$authors)) }}></span>
							<span class="tms-editor" {{ $post->editor('image_thumb', 'null', 'edit_post', array('type'=>'image', 'fieldLabel' => 'Image Thumb: 150x100')) }}></span>
							<span class="tms-editor" {{ $post->editor('main_image', 'null', 'edit_post', array('type'=>'image')) }}></span>
							<span class="tms-editor" {{ $post->editor('posted_on', 'null', 'edit_post', array('type'=>'date')) }}></span>
							<span class="tms-editor" {{ $post->editor('meta_title', null, 'edit_post') }}></span>
							<span class="tms-editor" {{ $post->editor('meta_keywords', null, 'edit_post', array('type' => 'text')) }}></span>
							<span class="tms-editor" {{ $post->editor('meta_description', null, 'edit_post') }}></span>
							<span class="tms-editor" {{ $post->editor('headline', 'null', 'edit_post')}}></span>
							<button class="tms-editor tms-btn-success" {{ $post->editor('article', 'null', 'edit_post', array('type'=>'wysiwyg')) }}>Edit This Post</button>

							<button class="tms-editor tms-btn-danger" {{ $post->deleteThing(null) }}>Remove Post</button>
						</div>
					<?php } ?>

					@if(isset($post->author) && $post->author != null && $post->author != '')
					<div class="bt bb">
						<img class="mt h20" src="{{ URL::asset('images/profile-'.str_replace(' ', '-', $post->author->name).'.jpg') }}">
						<p class="mt h20">By</p>
						<p class="sub-title mb">{{ $post->author->name }}</p>
						<p>{{ $post->author->title }}</p>
						<p class="sub-title mt h20">Share</p>
						<div class="addthis_toolbox addthis_default_style addthis_32x32_style" style="width:200px;margin:0 auto 20px;">
							<a class="addthis_button_facebook"></a>
							<a class="addthis_button_twitter"></a>
							<a class="addthis_button_google_plusone_share"></a>
							<a class="addthis_button_pinterest_share"></a>
							<a class="addthis_button_linkedin"></a>
						</div>
					</div>
					@endif
				</div>
			</div>
		</div>
	</section>

@stop

@section('modals')
	<div id="modal-video" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="Video Modal" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
	  <div class="modal-body">
	    <video id="video-player" controls="true" preload="none" width="527">
	      <p>Your user agent does not support the HTML5 Video element.</p>
	    </video>
	  </div>
	</div>
@stop